export const searchCache: Record<string, string[]> = {
  "provider:rust": [
    "Rust Programming Language",
    "Systems Programming",
    "Memory Safety",
    "Concurrency",
    "Performance Optimization",
    "Cargo (build system)"
  ],
  "provider:python": [
    "Python Programming",
    "Object-Oriented Programming (OOP)",
    "Data Structures & Algorithms",
    "Web Development",
    "Backend Development",
    "API Development",
    "Data Science",
    "Machine Learning",
    "Scripting & Automation",
    "Database Management"
  ],
  "seeker:sveltekit dev": [
    "SvelteKit",
    "Svelte",
    "JavaScript",
    "TypeScript",
    "HTML",
    "CSS",
    "Frontend Development",
    "Node.js",
    "Git",
    "API Integration",
    "Server-Side Rendering (SSR)",
    "Static Site Generation (SSG)",
    "Component-Based Architecture",
    "Web Development"
  ],
  "provider:ai b2b saas": [
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Data Science",
    "MLOps",
    "Cloud Computing",
    "Microservices Architecture",
    "API Development",
    "Backend Development",
    "Scalability Engineering",
    "System Architecture",
    "DevOps Practices",
    "Python Programming",
    "Database Management",
    "SaaS Product Development",
    "B2B Solutions",
    "Enterprise Software Development",
    "Predictive Analytics"
  ],
  "provider:touchngo but for poor countries": [
    "FinTech Development",
    "Mobile Payments",
    "E-wallet Architecture",
    "Financial Inclusion Strategies",
    "Emerging Markets FinTech",
    "Payment Gateway Integration",
    "API Development",
    "Distributed Systems",
    "Security Engineering",
    "Fraud Detection",
    "Data Analytics",
    "USSD/SMS Gateway Integration",
    "Mobile Application Development",
    "Cloud Infrastructure Management",
    "Regulatory Compliance (FinTech)",
    "Agent Network Management"
  ],
  "seeker:sveltekit": [
    "SvelteKit",
    "Svelte",
    "JavaScript",
    "TypeScript",
    "Frontend Development",
    "HTML",
    "CSS",
    "Node.js",
    "Vite",
    "API Integration",
    "State Management",
    "Server-Side Rendering (SSR)",
    "Static Site Generation (SSG)",
    "Single Page Application (SPA)"
  ],
  "seeker:react dev": [
    "React.js",
    "JavaScript",
    "HTML",
    "CSS",
    "React State Management",
    "RESTful APIs",
    "Git",
    "Webpack",
    "NPM",
    "Component-based Architecture",
    "Testing"
  ]
};
