export const searchCache: Record<string, string[]> = {
  "provider:rust": [
    "Rust Programming Language",
    "Systems Programming",
    "Memory Safety",
    "Concurrency",
    "Performance Optimization",
    "Cargo (build system)"
  ],
  "provider:python": [
    "Python Programming",
    "Object-Oriented Programming (OOP)",
    "Data Structures & Algorithms",
    "Web Development",
    "Backend Development",
    "API Development",
    "Data Science",
    "Machine Learning",
    "Scripting & Automation",
    "Database Management"
  ],
  "seeker:sveltekit dev": [
    "SvelteKit",
    "Svelte",
    "JavaScript",
    "TypeScript",
    "HTML",
    "CSS",
    "Frontend Development",
    "Node.js",
    "Git",
    "API Integration",
    "Server-Side Rendering (SSR)",
    "Static Site Generation (SSG)",
    "Component-Based Architecture",
    "Web Development"
  ],
  "provider:ai b2b saas": [
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Data Science",
    "MLOps",
    "Cloud Computing",
    "Microservices Architecture",
    "API Development",
    "Backend Development",
    "Scalability Engineering",
    "System Architecture",
    "DevOps Practices",
    "Python Programming",
    "Database Management",
    "SaaS Product Development",
    "B2B Solutions",
    "Enterprise Software Development",
    "Predictive Analytics"
  ],
  "provider:touchngo but for poor countries": [
    "FinTech Development",
    "Mobile Payments",
    "E-wallet Architecture",
    "Financial Inclusion Strategies",
    "Emerging Markets FinTech",
    "Payment Gateway Integration",
    "API Development",
    "Distributed Systems",
    "Security Engineering",
    "Fraud Detection",
    "Data Analytics",
    "USSD/SMS Gateway Integration",
    "Mobile Application Development",
    "Cloud Infrastructure Management",
    "Regulatory Compliance (FinTech)",
    "Agent Network Management"
  ],
  "seeker:sveltekit": [
    "SvelteKit",
    "Svelte",
    "JavaScript",
    "TypeScript",
    "Frontend Development",
    "HTML",
    "CSS",
    "Node.js",
    "Vite",
    "API Integration",
    "State Management",
    "Server-Side Rendering (SSR)",
    "Static Site Generation (SSG)",
    "Single Page Application (SPA)"
  ],
  "seeker:react dev": [
    "React.js",
    "JavaScript",
    "HTML",
    "CSS",
    "React State Management",
    "RESTful APIs",
    "Git",
    "Webpack",
    "NPM",
    "Component-based Architecture",
    "Testing"
  ],
  "seeker:javascript dev": [
    "JavaScript",
    "ES6+",
    "HTML5",
    "CSS3",
    "React.js",
    "Node.js",
    "Express.js",
    "TypeScript",
    "RESTful APIs",
    "Asynchronous Programming",
    "Git",
    "Webpack",
    "npm",
    "Unit Testing",
    "Performance Optimization",
    "Frontend Development",
    "Backend Development",
    "Problem Solving",
    "Debugging",
    "Data Structures",
    "Algorithms",
    "Agile Methodologies"
  ],
  "seeker:i am looking for an investment banker with prior experience in any bulge bracket firms in london, toronto or the us": [
    "Financial Modeling",
    "Valuation",
    "Mergers & Acquisitions (M&A)",
    "Capital Markets",
    "Corporate Finance",
    "Due Diligence",
    "Deal Structuring",
    "Pitch Book Development",
    "Financial Analysis",
    "Industry Research",
    "Transaction Management",
    "Securities",
    "Risk Management",
    "Regulatory Compliance (Financial)",
    "Investment Banking"
  ],
  "seeker:i am looking for a bangla migrant worker who's willing to be underpaid": [],
  "seeker:an indian": [],
  "seeker:a software developer based in asia": [
    "Programming Languages",
    "Data Structures and Algorithms",
    "Version Control (Git)",
    "Software Development Life Cycle (SDLC)",
    "Database Management",
    "API Design and Development",
    "Object-Oriented Programming (OOP)",
    "Problem Solving",
    "Debugging",
    "Software Testing"
  ],
  "provider:i want to find a  company that provides me high salary in the engineering field": [
    "Problem Solving",
    "Analytical Thinking",
    "Technical Design",
    "Systems Thinking",
    "Programming",
    "Data Analysis",
    "Cloud Platforms",
    "Engineering Principles",
    "Project Management",
    "Technical Communication",
    "Automation"
  ],
  "provider:i know a bit of c": [
    "C Programming Language",
    "Procedural Programming",
    "Pointers",
    "Memory Management",
    "Data Structures",
    "Algorithms",
    "Compilers",
    "Debugging",
    "Systems Programming",
    "Embedded Systems"
  ],
  "seeker:javascript dev with react experience": [
    "JavaScript",
    "React",
    "Frontend Development",
    "Web Development",
    "HTML",
    "CSS"
  ]
};
